# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
cache:
  paths:
    - ~/.m2/repository/

jobs:
  build:

    runs-on: maven:3.8.3-openjdk-17
    steps:
    - name: Set up JDK 17
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run with Maven
      run: |
        mvn spring-javaformat:apply
        mvn package --file pom.xml

  test:
    runs-on: maven:3.8.3-openjdk-17
    needs: build

    steps:
    - name: Testing
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Test with Maven
      run: |
        mvn spring-javaformat:apply
        mvn test

